[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn demo_app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
incrementalBuilds = true
